version: "3"
services:

  manager:
     image: oprid/manager:1.0
     volumes:
       - ${OPRID_WWW}:/www
       -  bus:/bus
     tmpfs:
       - /state

  dns:
     image: oprid/dns:1.0
     ports:
       - ${OPRID_EXPOSE_IP}:${OPRID_EXPOSE_DNS_PORT}:53/tcp
       - ${OPRID_EXPOSE_IP}:${OPRID_EXPOSE_DNS_PORT}:53/udp
     depends_on:
       - manager
     volumes:
       -  bus:/bus

  php-fpm:
     image: oprid/php-fpm:7.4
     depends_on:
       - manager
     volumes:
       - ${OPRID_WWW}:/www
       - bus:/bus

  nginx:
     image: oprid/nginx:1.0
     ports:
       - ${OPRID_EXPOSE_IP}:${OPRID_EXPOSE_HTTP_PORT}:80
     environment:
        - OPRID_NGINX_DEBUG=no
     depends_on:
       - manager
       - dns
       - php-fpm
     tmpfs:
       - /vhost
     volumes:
       - ${OPRID_WWW}:/www
       - bus:/bus

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=oprid
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      default:
        aliases:
         - a.mysql.db
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - 8080:8080

volumes:
  bus:
  mariadb:
